version: '3.7'

services:
  db:
    container_name: "foodgram_db"
    image: postgres:12
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    container_name: "foodgram_web"
    image: maskalev/foodgram
    restart: always
    ports:
      - "8000:8000" 
    volumes:
      - ./static:/code/static/
      - ./media:/code/media/
    depends_on:
      - db
    env_file:
      - ./.env
  nginx:
    container_name: "foodgram_nginx"
    image: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./static:/code/static/
      - ./media:/code/media/
    depends_on:
      - web
