version: '3.7'

services:
  db:
    container_name: "foodgram_db"
    image: postgres:12
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    container_name: "foodgram_web"
    image: maskalev/foodgram:2023-03-18-11-53
    restart: always
    ports:
      - "8000:8000" 
    volumes:
      - ./logs:/code/logs/
      - ./static:/code/static/
      - ./media:/code/media/
    depends_on:
      - db
    env_file:
      - ./.env
  nginx:
    container_name: "foodgram_nginx"
    image: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d/foodgram.conf:/etc/nginx/conf.d/foodgram.conf
      - ./nginx/logs:/var/logs/nginx/
      - ./static:/code/static/
      - ./media:/code/media/
    depends_on:
      - web
