# Generated by Django 3.2.4 on 2021-06-15 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_rename_time_recipe_cooking_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='style',
            new_name='color',
        ),
    ]
