# Generated by Django 3.2.4 on 2021-06-22 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20210619_0948'),
        ('recipes', '0005_auto_20210621_1809'),
    ]

    operations = [
    ]
