# Generated by Django 3.2.4 on 2021-07-17 05:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_merge_0005_auto_20210619_0948_0005_auto_20210621_1809'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='recipeingredients',
            name='unique_link',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cooking time, min'),
        ),
        migrations.AlterField(
            model_name='recipeingredients',
            name='quantity',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantity'),
        ),
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.UniqueConstraint(fields=('author', 'title'), name='unique_author_title_link'),
        ),
        migrations.AddConstraint(
            model_name='recipeingredients',
            constraint=models.UniqueConstraint(fields=('recipe', 'ingredient'), name='unique_recipe_ingredient_link'),
        ),
    ]
