# Generated by Django 3.2.4 on 2021-07-17 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_alter_recipe_slug'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='recipe',
            name='unique_author_title_link',
        ),
        migrations.RemoveConstraint(
            model_name='recipeingredients',
            name='unique_recipe_ingredient_link',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique=True, verbose_name='Recipe slug'),
        ),
        migrations.AddConstraint(
            model_name='recipeingredients',
            constraint=models.UniqueConstraint(fields=('recipe', 'ingredient'), name='unique_link'),
        ),
    ]
